# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 928ce7c2989950229c0ce100d215e5a6febc922ce766a99a10c3db7ccb374629d50414aa0252592c8780faf31fc74e618401f85d49e8dd7924d51f99cb107743

test:
  secret_key_base: b7b70aef6df809b7f3eaef025c4e616ce1c6cff4fc1345e589508473c40d5eb469eb75013473b0ca4da551b7e5c5922f627d8a8d303aa504de03b4cc8e6f5091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
